version: "3"
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
